version: '3.4'

secrets:
  pgsql:
    file: ./etc/secrets/pgsql
  pgsql_repl:
    file: ./etc/secrets/pgsql_repl

services:
  sentinel:
    image: sorintlab/stolon:master-pg14
    command: gosu stolon stolon-sentinel --cluster-name stolon-cluster --store-backend=etcdv3 --store-endpoints http://etcd-00:2379 --log-level info
    environment:
      STOLONCTL_CLUSTER_NAME: stolon-cluster
      STOLONCTL_STORE_BACKEND: etcdv3
      STOLONCTL_STORE_ENDPOINTS: http://etcd-00:2379
    networks:
      - etcd_etcd
      - pgdb
    deploy:
      replicas: 1
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
      update_config:
        parallelism: 2
        delay: 30s
        order: stop-first
        failure_action: pause

  stolon-keeper-1:
    image: sorintlab/stolon:master-pg14
    hostname: stolon-keeper-1
    environment:
      PGDATA: /var/lib/postgresql/data
      STOLONCTL_CLUSTER_NAME: stolon-cluster
      STOLONCTL_STORE_BACKEND: etcdv3
      STOLONCTL_STORE_ENDPOINTS: http://etcd-00:2379
    volumes:
      - pgstolon-keeper-1:/var/lib/postgresql/data
    secrets:
      - pgsql
      - pgsql_repl
    command: gosu stolon stolon-keeper --pg-listen-address stolon-keeper-1 --pg-repl-username replication --uid stolonkeeper1 --pg-su-username postgres --pg-su-passwordfile /run/secrets/pgsql --pg-repl-passwordfile /run/secrets/pgsql_repl --data-dir /var/lib/postgresql/data --cluster-name stolon-cluster --store-backend=etcdv3 --store-endpoints http://etcd-00:2379 --log-level info
    networks:
      - etcd_etcd
      - pgdb
    deploy:
      replicas: 1
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 640M
        reservations:
          memory: 136M

  stolon-keeper-2:
    image: sorintlab/stolon:master-pg14
    hostname: stolon-keeper-2
    environment:
      PGDATA: /var/lib/postgresql/data
      STOLONCTL_CLUSTER_NAME: stolon-cluster
      STOLONCTL_STORE_BACKEND: etcdv3
      STOLONCTL_STORE_ENDPOINTS: http://etcd-00:2379
    volumes:
      - pgstolon-keeper-2:/var/lib/postgresql/data
    secrets:
      - pgsql
    command: gosu stolon stolon-keeper --pg-listen-address stolon-keeper-2 --pg-repl-username replication --uid stolonkeeper2 --pg-su-username postgres --pg-su-passwordfile /run/secrets/pgsql --pg-repl-passwordfile /run/secrets/pgsql --data-dir /var/lib/postgresql/data --cluster-name stolon-cluster --store-backend=etcdv3 --store-endpoints http://etcd-00:2379 --log-level info
    networks:
      - etcd_etcd
      - pgdb
    deploy:
      replicas: 1
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M
        reservations:
          memory: 128M

  stolon-haproxy:
    image: vskurikhin/stolon-haproxy
    container_name: stolon-standby-haproxy
    privileged: true
    hostname: stolon-standby-haproxy
    networks:
      - etcd_etcd
      - pgdb
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 128M
    ports:
      - "5432:35432"
      - "5433:45432"
      - "18181:18181"
    depends_on:
      - zookeeper
    environment:
      STOLONCTL_CLUSTER_NAME: stolon-cluster
      STOLONCTL_STORE_BACKEND: etcdv3
      STOLONCTL_STORE_ENDPOINTS: http://etcd-00:2379
    volumes:
      - /proc:/host/proc:ro
      - /sys/fs/cgroup:/host/cgroup:ro
    tmpfs:
      - /run
      - /tmp

volumes:
  pgstolon-keeper-1:
    driver: local
  pgstolon-keeper-2:
    driver: local

networks:
  etcd_etcd:
    external: true
  pgdb:
    driver: overlay
    driver_opts:
      encrypted: "true"
    internal: true
